### ISSUE TITLE
Warden Menu using Movement

### ISSUE THREAD

**Issue by RespawnGT** [edgegamers/Jailbreak#113]
Open the Warden Menu with the !w command
_Insert Warden Menu into this HTML Menu (it's open source)_
[Video](https://streamable.com/3vspr4)
[Source](https://github.com/oqyh/cs2-Kill-Sound/blob/bbed0959046acb461eecf9524664999fb1b97329/Kill_Sound.cs#L108)

### **1.Freeday** 
_You will choose player (Hint in chat: NameOfPlayer has a free day) + (give him green color)_
### **2.Special Days** 

> **1.Freeday (5:00) | 3 Round Cooldown**
> _All prisoners and guards are allowed to roam freely.
> Cell doors should open automatically.
> Hint in chat: Freeday has begun!!_
> 
> **2. Free for All (4:00)**
> _All teams are ignored
> All players are teleported into armory and frozen for 5 seconds
> During this freeze time, the warden is expected to give a quick announcement
> During this freeze time, all players should be invulnerable
> Hint in chat: Free for All has begun!!_
> 
>  **3. Warday (4:30)**
> _All players are teleported into armory
> CTs are frozen for 3 seconds
> Prisoners are frozen for 30 seconds 
> Hint in chat: Warday has begun!!_
> 
> **4. Hide and seek (7) **
> _Cell doors should open automatically.
> CTs are frozen for 40 seconds and have a black screen.
> Hint in chat: Hide and seek has begun!!_

### **3. Noblock** 
 _Turn On / Turn Off_

### **4. Paints** 
_Paints Tplayer certain colour of choosing (!purple !blue)_

### **5. Pardon** 
_Give pardon to a rebel_

**Comment by Mooshua** [comment]
This is certainly not a bad idea… I think my preferred implementation would be doing this as a UserCmd hook so we can stop them from moving while they’re in the menu (and eg. Accidentally falling off something).

Thanks for bringing this up!

**Comment by MSWS** [comment]
Not planned.
