### ISSUE TITLE
Add weapon drops to logs

### ISSUE THREAD

**Issue by MSWS** [edgegamers/Jailbreak#119]
https://github.com/edgegamers/Jailbreak/pull/112

**Comment by MSWS** [comment]
Awaiting testing from CS Leadership.

**Comment by santa0605** [comment]
Does not work. Logs show that

![Screenshot (189)](https://github.com/edgegamers/Jailbreak/assets/159988404/61833342-2676-4bd1-8220-a47ac5e6065c)

**Comment by ShookEagle** [comment]
Could this issue be assigned to me?

**Comment by ShookEagle** [comment]
#205
