### ISSUE TITLE
css_fire (ability to fire current warden)

### ISSUE THREAD

**Issue by P250** [edgegamers/Jailbreak#170]
Self-explanatory, should only work if there is an active warden and the executor has correct permissions.

Should it play a sound also?

**Comment by MSWS** [comment]
Was this not implemented in https://github.com/edgegamers/Jailbreak/issues/30 @P250 ?

**Comment by MSWS** [comment]
Ah, I see it was closed. I'll re-open that issue, please refer to the original from here on out.
