### ISSUE TITLE
[Bug] ST not showing up as green

### ISSUE THREAD

**Issue by ntm5** [edgegamers/Jailbreak#220]
## Brief
ST was not shown as green.

**(Your Brief Here)**

## Reproduction
N/A

**Comment by MSWS** [comment]
@ntm5 could you supply the steps to reproduce? If not I'll close this issue in ~48 hours.

**Comment by santa0605** [comment]
https://cdn.discordapp.com/attachments/697167443621052487/1262087064560734239/Replay_2024-07-14_12-42-32-00.01.45.568-00.01.53.152.mp4?ex=669551ac&is=6694002c&hm=2e90db35df5f1f1f25333aa83a8c2d617ea1a0fb439050a46b6b5900d421b527&

This skin is known to not turn green or red.

**Comment by MSWS** [comment]
> https://cdn.discordapp.com/attachments/697167443621052487/1262087064560734239/Replay_2024-07-14_12-42-32-00.01.45.568-00.01.53.152.mp4?ex=669551ac&is=6694002c&hm=2e90db35df5f1f1f25333aa83a8c2d617ea1a0fb439050a46b6b5900d421b527&
> 
> This skin is known to not turn green or red.

`This content is no longer available.` Are you able to re-upload this?

**Comment by santa0605** [comment]
Pmed you the video @MSWS

**Comment by MSWS** [comment]
![Video](https://get.msws.xyz/ego/Replay_2024-07-14_12-42-32-00.01.45.568-00.01.53.152.mp4)

**Comment by MSWS** [comment]
Bug does not seem to be recurring anymore.
