### ISSUE TITLE
Speedrunners day is super fun :D

### ISSUE THREAD

**Issue by CactusJoan** [edgegamers/Jailbreak#268]
1.
In a speedrunners day, the speedrunner be decided sudo-randomly by hours alive 
https://discord.com/channels/1164388143756218411/1164683326985076816/1270232595535495239

2.
In a speedrunners day, the starting location should be the location the warden called the command
Some of the spawns are scuffed

**Comment by MSWS** [comment]
1. Not planned
2. A new update will fix most of these issues, thus not planned.

Thank you for the suggestions regardless.
