### ISSUE TITLE
Last Request

### ISSUE THREAD

**Issue by MSWS** [edgegamers/Jailbreak#28]
Once the round has been trimmed down to only 2 prisoners alive, prisoners should be able to "LR" (have a Last Request) with the remaining CTs.

An LR should be started with the css_lr command, prompting the T to pick an LR to choose from (listed below) and an alive guard to have it with. LRs should be relatively short (1 minute MAX, ideally ~30 seconds each) games to avoid causing delay.

The T should be teleported to the CT when starting an LR, and both players should be granted temporary immunity (~2-3 seconds) to avoid cheese. Alternatively, we could define a "safe spot" for all maps and teleport both players to this safe spot.

Potential LR ideas:
- [x] Gun Toss - Try to throw the gun as far as possible in a given direction
- [x] Rock Paper Scissors
- [x] Knife Fight - Strip both players of all weapons / armor, set HP to 100, and give them knives
- [x] No Scope
- [x] 50/50 (Coinflip, let the CT pick the side to be "fair")
- [x] S4S (Shot for shot - the T and CT face off each other and take turns shooting one bullet each)
- [ ] Mag4Mag (Same as S4S, but with whole magazines)
- [ ] Race (the prisoner will pick two spots, and the CT and T will have to race from start to end)

If possible, LR customizations where appropriate (weapon choices for noscope, s4s, etc., lowgrav/superspeed for knife fight) would be great.

**Comment by destoer** [comment]
"LRs should be relatively short (1 minute MAX, ideally ~30 seconds each) games to avoid causing delay."

My old LR plugin has a failsafe on certain last requests to make sure they don't take too long i.e on dodgeball it gives a he grenade after around 30 seconds

**Comment by MSWS** [comment]
Will be working on this on [feat/lr](https://github.com/edgegamers/Jailbreak/tree/feat/lr)

**Comment by MSWS** [comment]
https://github.com/edgegamers/Jailbreak/issues/44
