### ISSUE TITLE
Mute System

### ISSUE THREAD

**Issue by MSWS** [edgegamers/Jailbreak#29]
- [x] The warden should be able to temporarily mute players using a css_peace command.
- [x] At round start, all prisoners should be muted.
- [x] When the **first** warden is assigned, all players (except the warden) should be muted for 10 seconds.
- [x] Depending on the # of prisoners, prisoners should be unmuted after 60 - 90 seconds.
- [x] No matter what, dead players should never be able to talk.
- [x] (Optional): Admins should be able to talk over peace, silences, and dead mutes.

**Comment by P250** [comment]
Hi, I would like to start on this system. I was playing jb today and it's unbearable when you can't hear the warden! Please could this issue be assigned to me?

**Comment by MSWS** [comment]
@P250 I've gone ahead and assigned it.

**Comment by Spock8901** [comment]
muting dead/alive people works now so is it possible to make it when someone dies they're muted automatically but it doesnt spam chat? then once the round is over what ever happens next can be like that

**Comment by P250** [comment]
> muting dead/alive people works now so is it possible to make it when someone dies they're muted automatically but it doesnt spam chat? then once the round is over what ever happens next can be like that

Yes I think I like this idea. I think that once a player dies during the round they should be voice muted but still able to speak in the chat (to other dead players). I also think the alive players shouldn’t see the dead chat. Once the round ends all players are unmuted. Does this sound okay? :)

**Comment by Spock8901** [comment]
> > muting dead/alive people works now so is it possible to make it when someone dies they're muted automatically but it doesnt spam chat? then once the round is over what ever happens next can be like that
> 
> Yes I think I like this idea. I think that once a player dies during the round they should be voice muted but still able to speak in the chat (to other dead players). I also think the alive players shouldn’t see the dead chat. Once the round ends all players are unmuted. Does this sound okay? :)

just keep in mind if its an admin they'll need to be unmuted, but a dead VC will be chaotic ngl i suggest that it just be when they get muted but thats up to tech if they wanna have it like that.
