### ISSUE TITLE
Warden Removal Command (css_fire)

### ISSUE THREAD

**Issue by MSWS** [edgegamers/Jailbreak#30]
Admins (@css/generic) should be able to remove the current warden.
This should print to everyone that the warden was _fired_, and not killed (ie it is not a freeday).

Command: css_fire

**Comment by P250** [comment]
I'd like to do this one please, I don't think it'll be too difficult..!

**Comment by Mooshua** [comment]
Implemented in #74

**Comment by MSWS** [comment]
> Self-explanatory, should only work if there is an active warden and the executor has correct permissions.
> 
> Should it play a sound also?

@P250 to answer your actual question, the sound played when the warden passes should also be played for when they are fired.
