### ISSUE TITLE
Special Days

### ISSUE THREAD

**Issue by MSWS** [edgegamers/Jailbreak#31]
A special day is a day that the warden can initiate in the beginning 30 seconds of the round (not of becoming warden). Each special day should automatically handle the logic and work independently of other special days.

Commands:
css_sd - (Warden Only) - Displays the list of special days and begins a special day.

Generic Behavior:
- Upon calling, all players are frozen for a minimum of 3 seconds
- The type of special day should be broadcasted in chat
- There must be a minimum of 3 rounds between any special days, but each day can have a longer cooldown between the same day being called.

For example, if SD A, B, and C have respective cooldowns of 3, 5, 9, then assuming R represents a regular day...

Valid day rotations:
- 3 Regular, 1 B, 3 Regular, 1 C, 3 Regular, 1 A
- 3 Regular, 1 C, 3 Regular, 1 B, 3 Regular, 1 A
- 3 Regular, 1 A, 3 Regular, 1 C

Invalid day rotations:
- 3 Regular, 1 B, 2 Regular, 1 A [There were only 2 rounds from the last special day]
- 2 Regular, 1 A [There were only 2 rounds from the map beginning]
- 3 Regular, 1 B, 3 Regular, 1 B [The B Special Day required 5 rounds between it]

List of possible special days:

- [ ] Freeday (5:00) | 3 Round Cooldown
  - All prisoners and guards are allowed to roam freely.
  - Cell doors should open automatically.
- [ ] Free for All (4:00)
  - All teams are ignored
  - All players are teleported into armory and frozen for **5** seconds
    - During this freeze time, the warden is expected to give a quick announcement
    - During this freeze time, all players should be invulnerable
- [ ] Warday (4:30)
  - All players are teleported into armory
  - CTs are frozen for 3 seconds
  - Prisoners are frozen for 30 seconds

**Comment by abarnes6** [comment]
If no one has claimed this, I can attempt, but it might take a few weeks since I have classes.

**Comment by MSWS** [comment]
@abarnes6 feel free to take it!

Let me know if you have any questions.

**Comment by abarnes6** [comment]
I still haven't been able to do much on this, so if someone wants to take it in the meantime feel free.

**Comment by ntm5** [comment]
Started working on this [here](https://github.com/edgegamers/Jailbreak/pull/127)

**Comment by MSWS** [comment]
Thanks @ntm5 !
