### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by OfficialAudite** [edgegamers/Jailbreak#310]
## Brief

!lr, if people gets teleported then one into each other...

## Reproduction

- [x] This bug can be reproduced reliably
- [ ] This bug can be reproduced sometimes
- [ ] This bug is completely random
- [ ] I don't know how to reproduce it

1. Start server with this plugin
2. 1v1 type !lr
3. Choose shot for shot
4. gg

**Comment by MSWS** [comment]
This is intended behavior

**Comment by OfficialAudite** [comment]
Yeah but you get stuck!
