### ISSUE TITLE
Last Guard

### ISSUE THREAD

**Issue by MSWS** [edgegamers/Jailbreak#32]
If the round started with 4 or more CTs, and the round has been trimmed down to only one CT alive, then Last Guard should be initiated. Last Guard implies that the warden (and CTs) has failed to maintain control of the prisoners, and thus the "last guard" is tasked with **killing the remaining prisoners**, down to enough to LR (2 remaining).

The moment the second to last CT dies (meaning there is only one left alive):
- The CT should be given a health bonus relative to the remaining health of all other prisoners.
- An announcement should be made in chat that Last Guard has activated.
- The round time should be set to a dynamic time depending on the number of remaining prisoners alive.

Once the Last Guard has killed all the Ts down to two, Last Request (LR) should begin as normal.
If the Last Guard dies, the round should end as a T win.

**Comment by Spock8901** [comment]
Could it be possible to have it announce that its last guard? So that players arent confused on why they're getting killed when it is? Cause I usually forget to announce its Last Guard when there are sufficent guards on CT.

**Comment by MSWS** [comment]
@Spock8901 once Last Guard is actually implemented yes, it would be announced.

**Comment by P250** [comment]
Hi I'd like to take this one please!

**Comment by ntm5** [comment]
Ill take this

**Comment by ntm5** [comment]
@MSWS yeah I've made a good progress I'll make a pr next week
