### ISSUE TITLE
Warden Sounds

### ISSUE THREAD

**Issue by MSWS** [edgegamers/Jailbreak#33]
When a new warden is assigned, or an active warden dies, there should be a **very obvious** sound indicating so.

Will likely have to trudge through CS2's existing built-in sounds to find one that will work for everyone.

**Comment by jithatsonei** [comment]
Best way to go about this would be to create our own resource addons with custom sounds, from there we have the ability to adjust volume and set type (for most we will set to music so that players can control the volume via `snd_musicvolume`)

**Comment by Mooshua** [comment]
https://github.com/Source2ZE/CS2Fixes/pull/188
