### ISSUE TITLE
Special Treatment

### ISSUE THREAD

**Issue by MSWS** [edgegamers/Jailbreak#34]
The warden should be able to assign special treatment (STs) to prisoners.

Command:
- css_st [player] - Mark a player having special treatment, running the command on someone that already has ST should remove it

Behavior:
Upon giving ST, the player should be notified they have ST, and should have a center message being printed reaffirming this.
If an ST causes damage to a CT (ie becomes a rebel), their ST should be removed and they should become a rebel.

An ST should appears as (ST) instead of (Prisoner) in logs.

Limitations:
STs should be removed upon round start.

**Comment by Spock8901** [comment]
so i just realized and idk if itll help a little bit more, but isnt ST like warden but just a few more lines of coding? and changing the color and limit?
