### ISSUE TITLE
Warden Health and Armor

### ISSUE THREAD

**Issue by MSWS** [edgegamers/Jailbreak#36]
The **first** warden should be given 125 HP and 125 armor.

Subsequent warden should not be given this boost.

If the warden passes or is fired, their HP and armor should be decreased to 100 HP and 0 armor. If their HP is already lower than 100 HP, no action should be taken.

**Comment by P250** [comment]
I’d like to program this and branch from main so the changes could be applied very easily.

**Comment by P250** [comment]
I think this can probably be closed now! :)
