### ISSUE TITLE
Add Bomb/C4 rebel device

### ISSUE THREAD

**Issue by zahes1** [edgegamers/Jailbreak#38]
The bomb that T's receive should be able to be used by pressing "+use" with the bomb out. The bomb should make an indicator sound when used, then a second later explode. This bomb should do damage in a radius around the T to CT's only. The T should then be killed.

**Comment by MSWS** [comment]
Pending https://github.com/edgegamers/Jailbreak/issues/33

**Comment by Mooshua** [comment]
For now, implementing the mechanic as an instant and no-warning explosion might be interesting, albeit it would need to be nerfed to prevent instant team wipes.

Maybe the C4 countdown (beep beep beep) might work?

**Comment by P250** [comment]
If possible I think I am interested in taking this feature please!

**Comment by MSWS** [comment]
@P250 could you finish up and finalize your existing issues / PRs before starting work on other features?

**Comment by Mooshua** [comment]
Did we ever pin down the cause of the crashes during testing?

**Comment by P250** [comment]
> Did we ever pin down the cause of the crashes during testing?

Yes sir, check the fix/jihad branch. It was because I was using _basePlugin.AddTimer(), and for some reason the code I ran inside of that caused the crash. I changed it to Server.RunOnTick(1 second worth of ticks, () => ...)

**Comment by P250** [comment]
Implemented in #169
