### ISSUE TITLE
Server Messages

### ISSUE THREAD

**Issue by santa0605** [edgegamers/Jailbreak#42]
We should add messages that pop up in chat giving the link to our server rules, discord, how to get an E tag, and website.

This would hopefully bring more traffic to our discord and make players more aware of the rules.

**Comment by Mooshua** [comment]
This feels like it would be better addressed with a specific plugin for the job. Leaving open for now to see if anyone has a valid gamemode-specific use case (such as using it to post rule links, etc.)
