### ISSUE TITLE
Barebones LR Testing

### ISSUE THREAD

**Issue by MSWS** [edgegamers/Jailbreak#44]
# LR System

## Implemented LRs
- [ ] Knife Fight
- [ ] Gun Toss
- [ ] No Scope
- [ ] Rock Paper Scissors
- [ ] Coinflip
- [ ] Shot for Shot

## LR Checklist
- [ ] Ensure !lr can only be ran when there are 2 or fewer prisoners alive
- [ ] Ensure !lr can be ran if the round begins with only 2 or fewer prisoners alive
- [ ] Ensure !lr can only be ran by
  - [ ] Alive
  - [ ] Prisoners
  - [ ] Who are not already in an LR
- [ ] Ensure !lr opens up the corresponding menu(s)
  * [ ] !lr should open up an LR menu
  * [ ] !lr \[LR\] should open up a player selection menu
  * [ ] Selecting an LR in the LR menu should open up the player selection menu
  * [ ] Doing !lr \[LR\] \[Player\] should not open up any menus
- [ ] Ensure the knife LR shows up in the menu
- [ ] Ensure the menu works properly
  * [ ] Upon selecting the knife LR, the menu should show the player menu
  * [ ] Upon selecting a player, the LR should begin
- [ ] Ensure the LR works properly
  * [ ] Upon start, both players (the prisoner and selected guard) are stripped of weapons
  * [ ] After a small delay (3 seconds), both players are given a knife
  * [ ] Upon death of CT, the prisoner can run !lr again
  * [ ] Upon death of T, nothing should happen (the T should of course be dead), and the CT should be !lr -able again

**Comment by santa0605** [comment]
The command isn't working at all. Only /guntoss works

**Comment by MSWS** [comment]
- [ ] Ensure damaging the CT while in LR does not mark you as a rebel
- [ ] Ensure you cannot damage other players while you are in an LR
- [ ] Ensure you cannot be damaged by other players while you are in an LR
- [ ] Ensure all LRs can not be infinitely delayed / chesed
  - A specific example could be shot for shot, depending on implementation, if the prisoner starts with a shot and does not shoot, ensure the guard is not automatically slain in the event of a tie.
- [ ] Ensure slaying as a T / CT ends the LR and marks the winner appropriately

**Comment by MSWS** [comment]
Awaiting testing from CS Leadership.

**Comment by CSJacko** [comment]
[•] = Tested and working as intended
[?] = Needs more testing
[ ] = Not working as intended
--------------------------------------------------------

> # LR System
> ## Implemented LRs
> 
>     * [•]  Knife Fight
> 
>     * [•]  Gun Toss
> 
>     * [•]  No Scope
> 
>     * [•]  Rock Paper Scissors
> 
>     * [•]  Coinflip
> 
>     * [•]  Shot for Shot
> 
> 
> ## LR Checklist
> 
>     * [•]  Ensure !lr can only be ran when there are 2 or fewer prisoners alive
> 
>     * [•]  Ensure !lr can be ran if the round begins with only 2 or fewer prisoners alive
> 
>     * [•]  Ensure !lr can only be ran by
>       
>       * [•]  Alive
>       * [•]  Prisoners
>       * [?]  Who are not already in an LR **_(Needs further testing)_**
> 
>     * [•]  Ensure !lr opens up the corresponding menu(s)
>       
>       * [•]  !lr should open up an LR menu
>       * [•]  !lr [LR] should open up a player selection menu
>       * [•]  Selecting an LR in the LR menu should open up the player selection menu
>       * [•]  Doing !lr [LR] [Player] should not open up any menus
> 
>     * [•]  Ensure the knife LR shows up in the menu
> 
>     * [•]  Ensure the menu works properly
>       
>       * [•]  Upon selecting the knife LR, the menu should show the player menu
>       * [•]  Upon selecting a player, the LR should begin
> 
>     * [•]  Ensure the LR works properly
>       
>       * [•]  Upon start, both players (the prisoner and selected guard) are stripped of weapons
>       * [•]  After a small delay (3 seconds), both players are given a knife
>       * [?]  Upon death of CT, the prisoner can run !lr again **_(Needs further testing with more players)_**
>       * [•]  Upon death of T, nothing should happen (the T should of course be dead), and the CT should be !lr -able again



> * [•]  Ensure damaging the CT while in LR does not mark you as a rebel 
> 
>     * []  Ensure you cannot damage other players while you are in an LR **_(You are able to damage other non-LRing players while in LR)_**
> 
>     * []  Ensure you cannot be damaged by other players while you are in an LR **_(You can take damage from other non-lring players while in an LR)_**
> 
>     * [?]  Ensure all LRs can not be infinitely delayed / chesed **_(Needs further testing)_**
>       
>       * A specific example could be shot for shot, depending on implementation, if the prisoner starts with a shot and does not shoot, ensure the guard is not automatically slain in the event of a tie.
> 
>     * [•]  Ensure slaying as a T / CT ends the LR and marks the winner appropriately

**Comment by CSJacko** [comment]
• Mag 4 Mag and Race are showing up in the next page in LR list, however, when attempting to choose this LR it says in chat an error has occurred. 

• Chat only indicates to the LRing players if they have been chosen to LR when it should notify everyone. For example, if Prisoner _A_ chooses to LR Guard _B_, Prisoner _C_ should see in chat and LR has commenced instead of only alerting to player _A_ and _B_.

**Comment by CSJacko** [comment]
Players should receive a knife when an LR commences. For example, if Gun toss is chosen, both players are stripped of weapons and given a deagle after a short delay with no knife.

**Comment by CSJacko** [comment]
Players should receive a knife when an LR commences. For example, if Gun toss is chosen, both players are stripped of weapons and given a deagle after a short delay with no knife.

**Comment by CSJacko** [comment]
**Retested today (March 17 2024)**

### _Suggestions:_
- **Disable Race and Mag 4 Mag**
These LR's are not working correctly and I dont think we need to continue wasting time on trying to get them to work. Mag 4 Mag was never a popular LR to begin with and Race LR was always cheesed someway by the T's. 

- **Restore HP and strip armor after the LR has commenced**

- **Set both LR'ing players to a same player model color to be able to differentiate who you are LR'ing with**
If Prisoner _A_ chooses to LR Guard _B_, their player model color should be set to a similar color to be able to easily tell who they are LR'ing. This can be an alternative to beacons for the time being.

- **Receive a knife after LR has finished.**
Whoever wins in an LR should receive a knife once it has ended. 

- **Add a admin command to be able to !cancellr**

### _Known issues:_
- **Non-LR participants can still damage LR'ing players and vice versa.**

- **The type of LR and who is in the LR is not displaying to every player, only the 2 players in an active LR**
Everyone on the server should be able to see if an LR has been selected and who is in the LR. It should not only display to the 2 active LR'ing players.
