### ISSUE TITLE
[Bug] Spawn in armory / Join guard team without queue

### ISSUE THREAD

**Issue by ntm5** [edgegamers/Jailbreak#63]
## Brief
As the title says you can spawn in the armory as a terrorist.

## Reproduction

- [ ] This bug can be reproduced reliably
When a new round begins you go onto the Choose Teams menu and press "Choose Automatically". Afterward, you will be put in the armory. Tested on two different maps and it worked on both. 

If it is done later into the round you will be put in the guard team effectively skipping the whole queue.

## Additional Information
https://medal.tv/games/counter-strike-2/clips/1XJUPtTkcQEF0F/d1337uwjYGBX?invite=cr-MSx3NWssMjE3NjIzMTU5LA

**Comment by ntm5** [comment]
You can use the same concept to respawn after dying

**Comment by abarnes6** [comment]
PR created for this: https://github.com/edgegamers/Jailbreak/pull/81
