### ISSUE TITLE
MFK ban command

### ISSUE THREAD

**Issue by Spock8901** [edgegamers/Jailbreak#75]
We need /mfk back on the server if possible its really helpful back in GO cause we need to use it asap true menu options are weirder now but still basic functions exist. instead of making it an actual menu for the first half can it be /mfk <user|userid>, then it swaps em to Spec until we can confirm we want to ban them for MFK by hopefully doing /mfk <user|userid> confirm. if its possible then yay if not the menu options can be brought in.

**Comment by MSWS** [comment]
Out of scope of Jailbreak.
