### ISSUE TITLE
VC Mute 

### ISSUE THREAD

**Issue by Spock8901** [edgegamers/Jailbreak#76]
When admins mute other players it should be removed once a new round begins but its not happening and we have to keep unmuting them.
There should also be a notification that says they're muted like they're rebelling but says they're muted when attempting to speak or just have it saying they're muted the entire time and not flashing(idk thats another idea)

muting dead/alive people works now so is it possible to make it when someone dies they're muted automatically but it doesnt spam chat?

with peace soonTM i feel like something should be like this?

**Comment by MSWS** [comment]
The first part of your issue is out of scope, Jailbreak doesn't offer any moderation features like mute commands.

Muting while dead is currently [in the works](https://github.com/edgegamers/Jailbreak/issues/29), please comment on that issue and suggest this idea to the developer assigned to it.
