### ISSUE TITLE
CT Bans say expired well after being force removed

### ISSUE THREAD

**Issue by CrazyStill** [edgegamers/Jailbreak#99]
## Brief
If I CT ban someone, then unctban them, after the time passes that I originally banned them for it will say "user has been un CT banned" even tho I unctbanned them long ago. 

## Reproduction
CT ban the user for 15 minutes
UnCT Ban the user 
15 Minutes later it will say they have been unCT banned.

**Comment by MSWS** [comment]
Out of scope, this plugin does not handle CT Bans.
Has been noted for internal server tracking though.
